[package]
name = "squads-smart-account-program-types"
version = "0.1.0"
edition = "2021"
license-file = "../../LICENSE"
description = "Pure data types for the Squads Smart Account Program"

[lib]
name = "squads_smart_account_program_types"
crate-type = ["lib"]

[features]
default = ["instructions"]
borsh = ["dep:borsh", "solana-pubkey/borsh"]
anchor = ["borsh", "dep:anchor-lang"]
ephemeral-signers = ["solana-pubkey/curve25519"]
instructions = ["borsh", "dep:sha2"]
testing = []

[dependencies]
solana-pubkey = { version = "2.4.0", default-features = false }
borsh = { version = "0.10.3", optional = true }
anchor-lang = { version = "=0.32.1", optional = true, default-features = false, features = ["allow-missing-optionals"] }
sha2 = { version = "0.10", optional = true, default-features = false }
thiserror = "1"
