[package]
name = "squads-smart-account-program"
version = "0.1.0"
description = "Squads Smart Account Program V0.1"
edition = "2021"
license-file = "../../LICENSE"

[lib]
crate-type = ["cdylib", "lib"]
name = "squads_smart_account_program"

[features]
default = ["custom-heap"]
custom-heap = []
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
testing = ["squads-smart-account-program-types/testing"]

[dependencies]
anchor-lang = { version = "=0.32.1", default-features = false, features = ["allow-missing-optionals"] }
anchor-spl = { version = "=0.32.1", default-features = false, features = ["token", "token_2022", "mint"] }
solana-program = { version = "2.3.0", default-features = false, features = ["borsh"] }
solana-address-lookup-table-interface = { version = "2.2.2", default-features = false, features = ["bincode", "bytemuck"] }
solana-security-txt = "1.1.1"
squads-smart-account-program-types = { path = "../squads_smart_account_program_types", default-features = false, features = ["anchor", "ephemeral-signers"] }
