[toolchain]
anchor_version = "0.29.0" # `anchor-cli` version to use
solana_version = "1.18.16" # Solana version to use

[features]
seeds = false
skip-lint = false

[programs.localnet]
multisig = "GyhGAqjokLwF9UXdQ2dR5Zwiup242j4mX4J1tSMKyAmD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.account]]
address = "8UuqDAqe9UQx9e9Sjj4Gs3msrWGfzb4CJHGK3U3tcCEX"
filename = "tests/fixtures/pre-rent-collector/multisig-account.json"

[[test.genesis]]
address = "noopb9bkMVfRPU8AsbpTUg8AQkHtKwMYZiFUjNRtMmV"
program = "tests/fixtures/noop.so"

[scripts]
test = "npx mocha --node-option require=ts-node/register --extension ts -t 1000000 tests/index.ts"
test-proposals = "npx mocha --node-option require=ts-node/register --extension ts -t 1000000 tests/proposals.ts"
test-transactions = "npx mocha --node-option require=ts-node/register --extension ts -t 1000000 tests/transactions.ts"
test-batches = "npx mocha --node-option require=ts-node/register --extension ts -t 1000000 tests/batches.ts"
test-settings = "npx mocha --node-option require=ts-node/register --extension ts -t 1000000 tests/settings.ts"
test-sync = "npx mocha --node-option require=ts-node/register --extension ts -t 1000000 tests/sync-execution.ts"
test-policies = "npx mocha --node-option require=ts-node/register --extension ts -t 1000000 tests/policies.ts"
test-sdk = "npx mocha --node-option require=ts-node/register --extension ts -t 1000000 tests/sdk.ts"
test-accounts = "npx mocha --node-option require=ts-node/register --extension ts -t 1000000 tests/accounts.ts"
